server:
  port: 8083

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.148.166:3306/item?useUnicode=true&characterEncoding=utf8
    username: item
    password: SSnEKhWdzEfXhXnY
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: SSnEKhWdzEfXhXnY
    virtual-host: /

file-save-path: ./img

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true